import type {
  AchievementPreviewItem,
  DifficultyOption,
  DifficultyTuningMap,
  GameCardDescriptor,
  GameDifficulty,
  GameId,
  LeaderboardSeedRecord,
  PlayerStatsSummary,
} from '@/components/games/types';

export const GAME_STORAGE_KEY = 'typely-games-persistence-v1';

export const MAX_RECENT_RUNS = 40;

export const DIFFICULTY_OPTIONS: DifficultyOption[] = [
  {
    value: 'easy',
    label: 'Easy',
    helper: 'Slow pace, forgiving timers, best for warm up and beginners.',
  },
  {
    value: 'medium',
    label: 'Medium',
    helper: 'Balanced pressure with moderate spawn rates and speed ramps.',
  },
  {
    value: 'hard',
    label: 'Hard',
    helper: 'Aggressive pacing and tighter combo windows for advanced players.',
  },
  {
    value: 'extreme',
    label: 'Extreme',
    helper: 'Tournament intensity: fastest spawns, harsh penalties, max challenge.',
  },
];

export const DEFAULT_DIFFICULTY: GameDifficulty = 'medium';

export const GAME_CARDS: GameCardDescriptor[] = [
  {
    id: 'falling-words',
    title: 'Falling Words',
    subtitle: 'Typing Rain',
    description:
      'Words rain down with accelerating gravity. Type each word before it lands to preserve health and chain huge combos.',
    icon: 'CloudRain',
    accentClassName: 'text-primary',
    gradientClassName: 'from-primary/25 via-accent/20 to-secondary/25',
    playTimeLabel: '2-4 min rounds',
    difficultyHint: 'Best with rhythm focus',
    objectives: [
      'Clear falling words before impact',
      'Maintain streak for multiplier',
      'Survive difficulty ramps',
    ],
  },
  {
    id: 'speed-racer',
    title: 'Speed Racer',
    subtitle: 'Nitro Typing Run',
    description:
      'Your car accelerates with every accurate word. Mistakes drain momentum, while combos trigger nitro boosts and road blur effects.',
    icon: 'Car',
    accentClassName: 'text-accent',
    gradientClassName: 'from-accent/30 via-primary/20 to-secondary/20',
    playTimeLabel: '3 min sprint',
    difficultyHint: 'Best for speed training',
    objectives: ['Build velocity through accuracy', 'Avoid mistakes to keep top speed', 'Finish distance before timeout'],
  },
  {
    id: 'zombie-survival',
    title: 'Zombie Survival',
    subtitle: 'Typing Defense',
    description:
      'Incoming zombies carry words you must type to eliminate them. Survive waves, defeat bosses, and protect your base health.',
    icon: 'Skull',
    accentClassName: 'text-success',
    gradientClassName: 'from-success/25 via-primary/20 to-destructive/20',
    playTimeLabel: 'Wave based',
    difficultyHint: 'Best for focus under pressure',
    objectives: ['Type enemy words before contact', 'Clear waves and boss rounds', 'Manage health through sustained defense'],
  },
  {
    id: 'target-practice',
    title: 'Target Practice',
    subtitle: 'Precision Arena',
    description:
      'Moving word targets drift across the arena. Type them with precision to stack combo, maximize accuracy, and boost precision score.',
    icon: 'Crosshair',
    accentClassName: 'text-warning',
    gradientClassName: 'from-warning/20 via-primary/20 to-accent/25',
    playTimeLabel: '90 sec rounds',
    difficultyHint: 'Best for accuracy and precision',
    objectives: ['Hit moving targets quickly', 'Keep miss count low for precision bonus', 'Stabilize combo across target bursts'],
  },
];

export const DIFFICULTY_TUNING: DifficultyTuningMap = {
  fallingWords: {
    easy: {
      spawn: { minMs: 1050, maxMs: 1650 },
      baseWordSpeed: 62,
      maxConcurrentWords: 6,
      startingHealth: 120,
      scoreScale: 1,
    },
    medium: {
      spawn: { minMs: 780, maxMs: 1320 },
      baseWordSpeed: 84,
      maxConcurrentWords: 8,
      startingHealth: 110,
      scoreScale: 1.2,
    },
    hard: {
      spawn: { minMs: 560, maxMs: 1000 },
      baseWordSpeed: 108,
      maxConcurrentWords: 10,
      startingHealth: 100,
      scoreScale: 1.45,
    },
    extreme: {
      spawn: { minMs: 420, maxMs: 820 },
      baseWordSpeed: 130,
      maxConcurrentWords: 12,
      startingHealth: 92,
      scoreScale: 1.8,
    },
  },
  speedRacer: {
    easy: {
      startingSpeed: 72,
      accelerationGain: 13,
      maxSpeed: 188,
      speedDecayPerSecond: 8,
      mistakePenalty: 20,
      finishDistance: 920,
    },
    medium: {
      startingSpeed: 86,
      accelerationGain: 16,
      maxSpeed: 220,
      speedDecayPerSecond: 11,
      mistakePenalty: 24,
      finishDistance: 1050,
    },
    hard: {
      startingSpeed: 98,
      accelerationGain: 18,
      maxSpeed: 255,
      speedDecayPerSecond: 14,
      mistakePenalty: 28,
      finishDistance: 1225,
    },
    extreme: {
      startingSpeed: 112,
      accelerationGain: 20,
      maxSpeed: 280,
      speedDecayPerSecond: 18,
      mistakePenalty: 32,
      finishDistance: 1380,
    },
  },
  zombieSurvival: {
    easy: {
      spawn: { minMs: 1160, maxMs: 1820 },
      zombieSpeed: 14,
      bossIntervalWaves: 4,
      startingHealth: 135,
      laneCount: 4,
    },
    medium: {
      spawn: { minMs: 880, maxMs: 1520 },
      zombieSpeed: 18,
      bossIntervalWaves: 4,
      startingHealth: 120,
      laneCount: 4,
    },
    hard: {
      spawn: { minMs: 700, maxMs: 1260 },
      zombieSpeed: 22,
      bossIntervalWaves: 3,
      startingHealth: 110,
      laneCount: 5,
    },
    extreme: {
      spawn: { minMs: 540, maxMs: 1040 },
      zombieSpeed: 28,
      bossIntervalWaves: 3,
      startingHealth: 100,
      laneCount: 5,
    },
  },
  targetPractice: {
    easy: {
      spawn: { minMs: 900, maxMs: 1420 },
      maxTargets: 6,
      minRadius: 28,
      maxRadius: 42,
      targetSpeed: 48,
      roundTimeMs: 105000,
    },
    medium: {
      spawn: { minMs: 680, maxMs: 1180 },
      maxTargets: 8,
      minRadius: 24,
      maxRadius: 38,
      targetSpeed: 62,
      roundTimeMs: 96000,
    },
    hard: {
      spawn: { minMs: 520, maxMs: 960 },
      maxTargets: 10,
      minRadius: 20,
      maxRadius: 32,
      targetSpeed: 74,
      roundTimeMs: 90000,
    },
    extreme: {
      spawn: { minMs: 420, maxMs: 840 },
      maxTargets: 12,
      minRadius: 18,
      maxRadius: 28,
      targetSpeed: 88,
      roundTimeMs: 84000,
    },
  },
};

export const GAME_DIFFICULTY_CONFIG = {
  easy: {
    id: 'easy',
    label: 'Easy',
    description: 'Relaxed mode with gentle progression.',
    speedMultiplier: 0.82,
    spawnMultiplier: 0.8,
    healthMultiplier: 1.18,
    scoreMultiplier: 0.9,
    comboWindowMs: 1850,
    targetWpm: 30,
  },
  medium: {
    id: 'medium',
    label: 'Medium',
    description: 'Balanced challenge and learning pace.',
    speedMultiplier: 1,
    spawnMultiplier: 1,
    healthMultiplier: 1,
    scoreMultiplier: 1,
    comboWindowMs: 1550,
    targetWpm: 42,
  },
  hard: {
    id: 'hard',
    label: 'Hard',
    description: 'High pressure with rapid ramps.',
    speedMultiplier: 1.22,
    spawnMultiplier: 1.2,
    healthMultiplier: 0.92,
    scoreMultiplier: 1.24,
    comboWindowMs: 1320,
    targetWpm: 56,
  },
  extreme: {
    id: 'extreme',
    label: 'Extreme',
    description: 'Elite challenge with no breathing room.',
    speedMultiplier: 1.42,
    spawnMultiplier: 1.35,
    healthMultiplier: 0.86,
    scoreMultiplier: 1.46,
    comboWindowMs: 1120,
    targetWpm: 68,
  },
} as const;

export const DEFAULT_PLAYER_STATS: PlayerStatsSummary = {
  bestScore: 0,
  highestWpm: 0,
  bestAccuracy: 0,
  totalTimePlayedMs: 0,
  gamesCompleted: 0,
  totalRuns: 0,
  totalCorrectKeystrokes: 0,
  totalKeystrokes: 0,
  favoriteGame: 'falling-words',
  recentRuns: [],
  perGame: {
    'falling-words': {
      bestScore: 0,
      highestWpm: 0,
      bestAccuracy: 0,
      gamesCompleted: 0,
      totalTimePlayedMs: 0,
      totalRuns: 0,
      totalMistakes: 0,
      averageAccuracy: 0,
    },
    'speed-racer': {
      bestScore: 0,
      highestWpm: 0,
      bestAccuracy: 0,
      gamesCompleted: 0,
      totalTimePlayedMs: 0,
      totalRuns: 0,
      totalMistakes: 0,
      averageAccuracy: 0,
    },
    'zombie-survival': {
      bestScore: 0,
      highestWpm: 0,
      bestAccuracy: 0,
      gamesCompleted: 0,
      totalTimePlayedMs: 0,
      totalRuns: 0,
      totalMistakes: 0,
      averageAccuracy: 0,
    },
    'target-practice': {
      bestScore: 0,
      highestWpm: 0,
      bestAccuracy: 0,
      gamesCompleted: 0,
      totalTimePlayedMs: 0,
      totalRuns: 0,
      totalMistakes: 0,
      averageAccuracy: 0,
    },
  },
};

export const ACHIEVEMENT_PREVIEW_SEED: AchievementPreviewItem[] = [
  {
    id: 'first-1000',
    title: 'First 1K',
    description: 'Score a total of 1,000 points across all games.',
    progress: 0,
    goal: 1000,
    unlocked: false,
  },
  {
    id: 'combo-legend',
    title: 'Combo Legend',
    description: 'Reach a 30x combo in any game mode.',
    progress: 0,
    goal: 30,
    unlocked: false,
  },
  {
    id: 'night-rider',
    title: 'Night Rider',
    description: 'Hit 220 km/h in Speed Racer with nitro active.',
    progress: 0,
    goal: 220,
    unlocked: false,
  },
  {
    id: 'undead-hunter',
    title: 'Undead Hunter',
    description: 'Defeat 250 zombies in total.',
    progress: 0,
    goal: 250,
    unlocked: false,
  },
  {
    id: 'pinpoint',
    title: 'Pinpoint Precision',
    description: 'End Target Practice with at least 97% accuracy.',
    progress: 0,
    goal: 97,
    unlocked: false,
  },
  {
    id: 'marathon',
    title: 'Typing Marathon',
    description: 'Play games for a total of 90 minutes.',
    progress: 0,
    goal: 90,
    unlocked: false,
  },
];

export const GAME_ID_TO_LABEL: Record<GameId, string> = {
  'falling-words': 'Falling Words',
  'speed-racer': 'Speed Racer',
  'zombie-survival': 'Zombie Survival',
  'target-practice': 'Target Practice',
};

export const LEADERBOARD_SEED: LeaderboardSeedRecord[] = [
  { playerName: 'Avery', score: 1280, wpm: 44, accuracy: 96.1, gameId: 'falling-words', difficulty: 'easy' },
  { playerName: 'Kai', score: 1410, wpm: 49, accuracy: 95.2, gameId: 'falling-words', difficulty: 'easy' },
  { playerName: 'Jordan', score: 1675, wpm: 52, accuracy: 96.4, gameId: 'falling-words', difficulty: 'medium' },
  { playerName: 'Riley', score: 1732, wpm: 54, accuracy: 94.8, gameId: 'falling-words', difficulty: 'medium' },
  { playerName: 'Logan', score: 1811, wpm: 56, accuracy: 95.7, gameId: 'falling-words', difficulty: 'medium' },
  { playerName: 'Sloane', score: 1920, wpm: 57, accuracy: 96.2, gameId: 'falling-words', difficulty: 'hard' },
  { playerName: 'Casey', score: 2040, wpm: 59, accuracy: 95.4, gameId: 'falling-words', difficulty: 'hard' },
  { playerName: 'Parker', score: 2188, wpm: 61, accuracy: 94.7, gameId: 'falling-words', difficulty: 'hard' },
  { playerName: 'Quinn', score: 2321, wpm: 63, accuracy: 95.1, gameId: 'falling-words', difficulty: 'extreme' },
  { playerName: 'Taylor', score: 2418, wpm: 65, accuracy: 95.8, gameId: 'falling-words', difficulty: 'extreme' },
  { playerName: 'Skyler', score: 2510, wpm: 68, accuracy: 94.9, gameId: 'falling-words', difficulty: 'extreme' },

  { playerName: 'Mika', score: 1100, wpm: 41, accuracy: 93.7, gameId: 'speed-racer', difficulty: 'easy' },
  { playerName: 'Ari', score: 1265, wpm: 45, accuracy: 94.8, gameId: 'speed-racer', difficulty: 'easy' },
  { playerName: 'Noel', score: 1498, wpm: 48, accuracy: 95.3, gameId: 'speed-racer', difficulty: 'medium' },
  { playerName: 'Harper', score: 1630, wpm: 52, accuracy: 94.4, gameId: 'speed-racer', difficulty: 'medium' },
  { playerName: 'Reese', score: 1755, wpm: 55, accuracy: 94.9, gameId: 'speed-racer', difficulty: 'medium' },
  { playerName: 'Drew', score: 1901, wpm: 58, accuracy: 95.6, gameId: 'speed-racer', difficulty: 'hard' },
  { playerName: 'Finley', score: 2066, wpm: 61, accuracy: 94.3, gameId: 'speed-racer', difficulty: 'hard' },
  { playerName: 'Morgan', score: 2198, wpm: 64, accuracy: 95.1, gameId: 'speed-racer', difficulty: 'hard' },
  { playerName: 'Blake', score: 2344, wpm: 66, accuracy: 94.8, gameId: 'speed-racer', difficulty: 'extreme' },
  { playerName: 'Rowan', score: 2482, wpm: 69, accuracy: 95.4, gameId: 'speed-racer', difficulty: 'extreme' },
  { playerName: 'Cameron', score: 2595, wpm: 72, accuracy: 95.2, gameId: 'speed-racer', difficulty: 'extreme' },

  { playerName: 'Dakota', score: 1220, wpm: 43, accuracy: 95.8, gameId: 'zombie-survival', difficulty: 'easy' },
  { playerName: 'Alex', score: 1388, wpm: 46, accuracy: 94.9, gameId: 'zombie-survival', difficulty: 'easy' },
  { playerName: 'Jules', score: 1540, wpm: 50, accuracy: 95.7, gameId: 'zombie-survival', difficulty: 'medium' },
  { playerName: 'Remy', score: 1705, wpm: 53, accuracy: 94.6, gameId: 'zombie-survival', difficulty: 'medium' },
  { playerName: 'Hayden', score: 1860, wpm: 56, accuracy: 95.2, gameId: 'zombie-survival', difficulty: 'medium' },
  { playerName: 'Charlie', score: 1988, wpm: 58, accuracy: 94.8, gameId: 'zombie-survival', difficulty: 'hard' },
  { playerName: 'Robin', score: 2144, wpm: 60, accuracy: 95.1, gameId: 'zombie-survival', difficulty: 'hard' },
  { playerName: 'Shawn', score: 2296, wpm: 63, accuracy: 94.7, gameId: 'zombie-survival', difficulty: 'hard' },
  { playerName: 'Emerson', score: 2451, wpm: 66, accuracy: 95.0, gameId: 'zombie-survival', difficulty: 'extreme' },
  { playerName: 'Phoenix', score: 2609, wpm: 69, accuracy: 94.5, gameId: 'zombie-survival', difficulty: 'extreme' },
  { playerName: 'Alden', score: 2744, wpm: 73, accuracy: 95.1, gameId: 'zombie-survival', difficulty: 'extreme' },

  { playerName: 'Sawyer', score: 1180, wpm: 42, accuracy: 96.4, gameId: 'target-practice', difficulty: 'easy' },
  { playerName: 'Kendall', score: 1340, wpm: 45, accuracy: 95.8, gameId: 'target-practice', difficulty: 'easy' },
  { playerName: 'Rory', score: 1514, wpm: 49, accuracy: 96.1, gameId: 'target-practice', difficulty: 'medium' },
  { playerName: 'Spencer', score: 1682, wpm: 52, accuracy: 95.3, gameId: 'target-practice', difficulty: 'medium' },
  { playerName: 'Marlowe', score: 1831, wpm: 55, accuracy: 95.7, gameId: 'target-practice', difficulty: 'medium' },
  { playerName: 'Bailey', score: 1998, wpm: 58, accuracy: 95.9, gameId: 'target-practice', difficulty: 'hard' },
  { playerName: 'Peyton', score: 2142, wpm: 61, accuracy: 95.0, gameId: 'target-practice', difficulty: 'hard' },
  { playerName: 'River', score: 2279, wpm: 64, accuracy: 95.4, gameId: 'target-practice', difficulty: 'hard' },
  { playerName: 'Lennon', score: 2416, wpm: 67, accuracy: 95.2, gameId: 'target-practice', difficulty: 'extreme' },
  { playerName: 'Teagan', score: 2544, wpm: 70, accuracy: 95.6, gameId: 'target-practice', difficulty: 'extreme' },
  { playerName: 'Ellis', score: 2660, wpm: 74, accuracy: 95.1, gameId: 'target-practice', difficulty: 'extreme' },

  { playerName: 'Player01', score: 1277, wpm: 47, accuracy: 94.6, gameId: 'falling-words', difficulty: 'easy' },
  { playerName: 'Player02', score: 1326, wpm: 48, accuracy: 94.7, gameId: 'falling-words', difficulty: 'easy' },
  { playerName: 'Player03', score: 1375, wpm: 49, accuracy: 94.8, gameId: 'falling-words', difficulty: 'easy' },
  { playerName: 'Player04', score: 1424, wpm: 50, accuracy: 94.9, gameId: 'falling-words', difficulty: 'medium' },
  { playerName: 'Player05', score: 1473, wpm: 51, accuracy: 95.0, gameId: 'falling-words', difficulty: 'medium' },
  { playerName: 'Player06', score: 1522, wpm: 52, accuracy: 95.1, gameId: 'falling-words', difficulty: 'medium' },
  { playerName: 'Player07', score: 1571, wpm: 53, accuracy: 95.2, gameId: 'falling-words', difficulty: 'hard' },
  { playerName: 'Player08', score: 1620, wpm: 54, accuracy: 95.3, gameId: 'falling-words', difficulty: 'hard' },
  { playerName: 'Player09', score: 1669, wpm: 55, accuracy: 95.4, gameId: 'falling-words', difficulty: 'hard' },
  { playerName: 'Player10', score: 1718, wpm: 56, accuracy: 95.5, gameId: 'falling-words', difficulty: 'extreme' },
  { playerName: 'Player11', score: 1767, wpm: 57, accuracy: 95.6, gameId: 'falling-words', difficulty: 'extreme' },
  { playerName: 'Player12', score: 1816, wpm: 58, accuracy: 95.7, gameId: 'falling-words', difficulty: 'extreme' },
  { playerName: 'Player13', score: 1865, wpm: 59, accuracy: 95.8, gameId: 'speed-racer', difficulty: 'easy' },
  { playerName: 'Player14', score: 1914, wpm: 60, accuracy: 95.9, gameId: 'speed-racer', difficulty: 'easy' },
  { playerName: 'Player15', score: 1963, wpm: 61, accuracy: 96.0, gameId: 'speed-racer', difficulty: 'easy' },
  { playerName: 'Player16', score: 2012, wpm: 62, accuracy: 95.1, gameId: 'speed-racer', difficulty: 'medium' },
  { playerName: 'Player17', score: 2061, wpm: 63, accuracy: 95.2, gameId: 'speed-racer', difficulty: 'medium' },
  { playerName: 'Player18', score: 2110, wpm: 64, accuracy: 95.3, gameId: 'speed-racer', difficulty: 'medium' },
  { playerName: 'Player19', score: 2159, wpm: 65, accuracy: 95.4, gameId: 'speed-racer', difficulty: 'hard' },
  { playerName: 'Player20', score: 2208, wpm: 66, accuracy: 95.5, gameId: 'speed-racer', difficulty: 'hard' },
  { playerName: 'Player21', score: 2257, wpm: 67, accuracy: 95.6, gameId: 'speed-racer', difficulty: 'hard' },
  { playerName: 'Player22', score: 2306, wpm: 68, accuracy: 95.7, gameId: 'speed-racer', difficulty: 'extreme' },
  { playerName: 'Player23', score: 2355, wpm: 69, accuracy: 95.8, gameId: 'speed-racer', difficulty: 'extreme' },
  { playerName: 'Player24', score: 2404, wpm: 70, accuracy: 95.9, gameId: 'speed-racer', difficulty: 'extreme' },
  { playerName: 'Player25', score: 2453, wpm: 58, accuracy: 94.8, gameId: 'zombie-survival', difficulty: 'easy' },
  { playerName: 'Player26', score: 2502, wpm: 59, accuracy: 94.9, gameId: 'zombie-survival', difficulty: 'easy' },
  { playerName: 'Player27', score: 2551, wpm: 60, accuracy: 95.0, gameId: 'zombie-survival', difficulty: 'easy' },
  { playerName: 'Player28', score: 2600, wpm: 61, accuracy: 95.1, gameId: 'zombie-survival', difficulty: 'medium' },
  { playerName: 'Player29', score: 2649, wpm: 62, accuracy: 95.2, gameId: 'zombie-survival', difficulty: 'medium' },
  { playerName: 'Player30', score: 2698, wpm: 63, accuracy: 95.3, gameId: 'zombie-survival', difficulty: 'medium' },
  { playerName: 'Player31', score: 2747, wpm: 64, accuracy: 95.4, gameId: 'zombie-survival', difficulty: 'hard' },
  { playerName: 'Player32', score: 2796, wpm: 65, accuracy: 95.5, gameId: 'zombie-survival', difficulty: 'hard' },
  { playerName: 'Player33', score: 2845, wpm: 66, accuracy: 95.6, gameId: 'zombie-survival', difficulty: 'hard' },
  { playerName: 'Player34', score: 2894, wpm: 67, accuracy: 95.7, gameId: 'zombie-survival', difficulty: 'extreme' },
  { playerName: 'Player35', score: 2943, wpm: 68, accuracy: 95.8, gameId: 'zombie-survival', difficulty: 'extreme' },
  { playerName: 'Player36', score: 2992, wpm: 69, accuracy: 95.9, gameId: 'zombie-survival', difficulty: 'extreme' },
  { playerName: 'Player37', score: 3041, wpm: 57, accuracy: 95.5, gameId: 'target-practice', difficulty: 'easy' },
  { playerName: 'Player38', score: 3090, wpm: 58, accuracy: 95.6, gameId: 'target-practice', difficulty: 'easy' },
  { playerName: 'Player39', score: 3139, wpm: 59, accuracy: 95.7, gameId: 'target-practice', difficulty: 'easy' },
  { playerName: 'Player40', score: 3188, wpm: 60, accuracy: 95.8, gameId: 'target-practice', difficulty: 'medium' },
  { playerName: 'Player41', score: 3237, wpm: 61, accuracy: 95.9, gameId: 'target-practice', difficulty: 'medium' },
  { playerName: 'Player42', score: 3286, wpm: 62, accuracy: 96.0, gameId: 'target-practice', difficulty: 'medium' },
  { playerName: 'Player43', score: 3335, wpm: 63, accuracy: 95.1, gameId: 'target-practice', difficulty: 'hard' },
  { playerName: 'Player44', score: 3384, wpm: 64, accuracy: 95.2, gameId: 'target-practice', difficulty: 'hard' },
  { playerName: 'Player45', score: 3433, wpm: 65, accuracy: 95.3, gameId: 'target-practice', difficulty: 'hard' },
  { playerName: 'Player46', score: 3482, wpm: 66, accuracy: 95.4, gameId: 'target-practice', difficulty: 'extreme' },
  { playerName: 'Player47', score: 3531, wpm: 67, accuracy: 95.5, gameId: 'target-practice', difficulty: 'extreme' },
  { playerName: 'Player48', score: 3580, wpm: 68, accuracy: 95.6, gameId: 'target-practice', difficulty: 'extreme' },
  { playerName: 'Player49', score: 3629, wpm: 69, accuracy: 95.7, gameId: 'falling-words', difficulty: 'hard' },
  { playerName: 'Player50', score: 3678, wpm: 70, accuracy: 95.8, gameId: 'falling-words', difficulty: 'extreme' },
  { playerName: 'Player51', score: 3727, wpm: 71, accuracy: 95.9, gameId: 'speed-racer', difficulty: 'hard' },
  { playerName: 'Player52', score: 3776, wpm: 72, accuracy: 96.0, gameId: 'speed-racer', difficulty: 'extreme' },
  { playerName: 'Player53', score: 3825, wpm: 73, accuracy: 95.4, gameId: 'zombie-survival', difficulty: 'hard' },
  { playerName: 'Player54', score: 3874, wpm: 74, accuracy: 95.5, gameId: 'zombie-survival', difficulty: 'extreme' },
  { playerName: 'Player55', score: 3923, wpm: 75, accuracy: 95.6, gameId: 'target-practice', difficulty: 'hard' },
  { playerName: 'Player56', score: 3972, wpm: 76, accuracy: 95.7, gameId: 'target-practice', difficulty: 'extreme' },
  { playerName: 'Player57', score: 4021, wpm: 63, accuracy: 94.8, gameId: 'falling-words', difficulty: 'easy' },
  { playerName: 'Player58', score: 4070, wpm: 64, accuracy: 94.9, gameId: 'falling-words', difficulty: 'medium' },
  { playerName: 'Player59', score: 4119, wpm: 65, accuracy: 95.0, gameId: 'falling-words', difficulty: 'hard' },
  { playerName: 'Player60', score: 4168, wpm: 66, accuracy: 95.1, gameId: 'falling-words', difficulty: 'extreme' },
  { playerName: 'Player61', score: 4217, wpm: 67, accuracy: 95.2, gameId: 'speed-racer', difficulty: 'easy' },
  { playerName: 'Player62', score: 4266, wpm: 68, accuracy: 95.3, gameId: 'speed-racer', difficulty: 'medium' },
  { playerName: 'Player63', score: 4315, wpm: 69, accuracy: 95.4, gameId: 'speed-racer', difficulty: 'hard' },
  { playerName: 'Player64', score: 4364, wpm: 70, accuracy: 95.5, gameId: 'speed-racer', difficulty: 'extreme' },
  { playerName: 'Player65', score: 4413, wpm: 71, accuracy: 95.6, gameId: 'zombie-survival', difficulty: 'easy' },
  { playerName: 'Player66', score: 4462, wpm: 72, accuracy: 95.7, gameId: 'zombie-survival', difficulty: 'medium' },
  { playerName: 'Player67', score: 4511, wpm: 73, accuracy: 95.8, gameId: 'zombie-survival', difficulty: 'hard' },
  { playerName: 'Player68', score: 4560, wpm: 74, accuracy: 95.9, gameId: 'zombie-survival', difficulty: 'extreme' },
  { playerName: 'Player69', score: 4609, wpm: 75, accuracy: 95.2, gameId: 'target-practice', difficulty: 'easy' },
  { playerName: 'Player70', score: 4658, wpm: 76, accuracy: 95.3, gameId: 'target-practice', difficulty: 'medium' },
  { playerName: 'Player71', score: 4707, wpm: 77, accuracy: 95.4, gameId: 'target-practice', difficulty: 'hard' },
  { playerName: 'Player72', score: 4756, wpm: 78, accuracy: 95.5, gameId: 'target-practice', difficulty: 'extreme' },
  { playerName: 'Player73', score: 4805, wpm: 66, accuracy: 94.7, gameId: 'falling-words', difficulty: 'easy' },
  { playerName: 'Player74', score: 4854, wpm: 67, accuracy: 94.8, gameId: 'falling-words', difficulty: 'medium' },
  { playerName: 'Player75', score: 4903, wpm: 68, accuracy: 94.9, gameId: 'falling-words', difficulty: 'hard' },
  { playerName: 'Player76', score: 4952, wpm: 69, accuracy: 95.0, gameId: 'falling-words', difficulty: 'extreme' },
  { playerName: 'Player77', score: 5001, wpm: 70, accuracy: 95.1, gameId: 'speed-racer', difficulty: 'easy' },
  { playerName: 'Player78', score: 5050, wpm: 71, accuracy: 95.2, gameId: 'speed-racer', difficulty: 'medium' },
  { playerName: 'Player79', score: 5099, wpm: 72, accuracy: 95.3, gameId: 'speed-racer', difficulty: 'hard' },
  { playerName: 'Player80', score: 5148, wpm: 73, accuracy: 95.4, gameId: 'speed-racer', difficulty: 'extreme' },
  { playerName: 'Player81', score: 5197, wpm: 74, accuracy: 95.5, gameId: 'zombie-survival', difficulty: 'easy' },
  { playerName: 'Player82', score: 5246, wpm: 75, accuracy: 95.6, gameId: 'zombie-survival', difficulty: 'medium' },
  { playerName: 'Player83', score: 5295, wpm: 76, accuracy: 95.7, gameId: 'zombie-survival', difficulty: 'hard' },
  { playerName: 'Player84', score: 5344, wpm: 77, accuracy: 95.8, gameId: 'zombie-survival', difficulty: 'extreme' },
  { playerName: 'Player85', score: 5393, wpm: 78, accuracy: 95.9, gameId: 'target-practice', difficulty: 'easy' },
  { playerName: 'Player86', score: 5442, wpm: 79, accuracy: 96.0, gameId: 'target-practice', difficulty: 'medium' },
  { playerName: 'Player87', score: 5491, wpm: 80, accuracy: 95.3, gameId: 'target-practice', difficulty: 'hard' },
  { playerName: 'Player88', score: 5540, wpm: 81, accuracy: 95.4, gameId: 'target-practice', difficulty: 'extreme' },
  { playerName: 'Player89', score: 5589, wpm: 70, accuracy: 94.9, gameId: 'falling-words', difficulty: 'easy' },
  { playerName: 'Player90', score: 5638, wpm: 71, accuracy: 95.0, gameId: 'falling-words', difficulty: 'medium' },
  { playerName: 'Player91', score: 5687, wpm: 72, accuracy: 95.1, gameId: 'falling-words', difficulty: 'hard' },
  { playerName: 'Player92', score: 5736, wpm: 73, accuracy: 95.2, gameId: 'falling-words', difficulty: 'extreme' },
  { playerName: 'Player93', score: 5785, wpm: 74, accuracy: 95.3, gameId: 'speed-racer', difficulty: 'easy' },
  { playerName: 'Player94', score: 5834, wpm: 75, accuracy: 95.4, gameId: 'speed-racer', difficulty: 'medium' },
  { playerName: 'Player95', score: 5883, wpm: 76, accuracy: 95.5, gameId: 'speed-racer', difficulty: 'hard' },
  { playerName: 'Player96', score: 5932, wpm: 77, accuracy: 95.6, gameId: 'speed-racer', difficulty: 'extreme' },
  { playerName: 'Player97', score: 5981, wpm: 78, accuracy: 95.7, gameId: 'zombie-survival', difficulty: 'easy' },
  { playerName: 'Player98', score: 6030, wpm: 79, accuracy: 95.8, gameId: 'zombie-survival', difficulty: 'medium' },
  { playerName: 'Player99', score: 6079, wpm: 80, accuracy: 95.9, gameId: 'zombie-survival', difficulty: 'hard' },
  { playerName: 'Player100', score: 6128, wpm: 81, accuracy: 96.0, gameId: 'zombie-survival', difficulty: 'extreme' },
];
